### ISSUE TITLE
Text spacing issue

### ISSUE THREAD

**Issue by IeuanWalker** [SuavePirate/MarkdownTextView#5]
I need a way to display .md files and I find this control really good, but I have 2 issues (1 explained in another issue) and this one.

Basically, there is a huge amount of padding around headers and paragraphs.
Here is my XAML - 
```XAML
<ScrollView HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
    <mdview:MarkdownTextView BackgroundColor="Transparent"
                                Markdown="{Binding TestLbl}"
                                TextColor="White" />
</ScrollView>
```

![screenshot_20180305-171734](https://user-images.githubusercontent.com/6544051/36989545-e973267e-2099-11e8-84fc-e2e65d6d7df2.jpg)

**Comment by SuavePirate** [comment]
This is part of how Android handles applying formatted text, and they don't make it super customizable without a bit of headache. I'm working on a refactored version of this control that will give that sort of freedom and wrap the Android headaches.

**Comment by IeuanWalker** [comment]
@SuavePirate ahh that be awesome :)

**Comment by IeuanWalker** [comment]
Closing as no I no longer use this package
